logging:
  level:
    guru.springframework: debug

spring:
  flyway:
    enabled: false
#  jpa:
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-source: metadata
#              create-target: drop-and-create.sql
#              drop-target: drop-and-create.sql