logging:
  level:
    guru.springframework: debug
    org.springframework.security: trace

spring:
  flyway:
    enabled: false
#  jpa:
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-source: metadata
#              create-target: drop-and-create.sql
#              drop-target: drop-and-create.sql
  security:
    user:
      name: user1
      password: password


